### ISSUE TITLE
Error on viewing site

### ISSUE THREAD

**Issue by codeclinic** [hubertnguyen/memcachier#3]
Right now my site is giving me this error:

Fatal error: Class 'Memcache' not found in /home/dev/public_html/wp-content/object-cache.php on line 289

**Comment by hubertnguyen** [comment]
This means that your PHP does not have the Memcache/Memcached library installed. You should be able to google how to add this to your server.

**Comment by codeclinic** [comment]
Ah ok, I wasn't sure whether this was needed when using Memcachier. 

I know this is probably a bit out of scope but is memcache and memcached required? There seems to be a bit of conflicting info about this subject.

**Comment by hubertnguyen** [comment]
Memcachier supports both APIs, so either should work. You definitely need the Memcache PHP library because that's the code that PHP is using for instantiating the classes to use Memcache.

The PHP library reside on your server and that's what's talking to Memcachier.

**Comment by codeclinic** [comment]
As far as I can tell I do have Memcached installed, but Im still getting the same error. Here a php info that shows that memcached is installed. 

http://dev.codeclinic.de/memcached_test.php

Any suggestions?

**Comment by hubertnguyen** [comment]
You have support for memcacheD. The code requires support for Memcache (no D)
Check this: http://stackoverflow.com/questions/2659035/php-memcached-fatal-error-class-memcache-not-found

**Comment by codeclinic** [comment]
I was aware of the two packages but it seems even people writing tutorials don't fully know what they are doing. Even the accepted answer on the SO post you referenced, talks of needing to install 'memcache' and then explains how to do it (eg 'sudo apt-get memcached php5-memcached') which is wrong.

Anyway, I guessed at running 'sudo apt-get php5-memcache' and the site runs without that error. So it would appear things are working now.

Thanks for the help.

**Comment by hubertnguyen** [comment]
You're welcome. The perils of community support I guess, but I'm glad to see that it's working now.

Maybe the SO answer works on their flavor of Linux? If not, you could add a note for the next person who comes along.

**Comment by codeclinic** [comment]
I already did that, Im less of an SO noob than I am a php noob. ;-)
